DATA_PATHS:
  videos_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/data/volleyball/volleyball_/videos"
  annot_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/data/volleyball/volleyball_tracking_annotation/volleyball_tracking_annotation"
  pooled_players_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/pooled_players_features"
  frame_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/frame_level_features"
  player_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/player_level_features"

TARGET_VIDEOS:
  train_ids: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31,
                 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_ids: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]

EXTRACTED_FEATURES_SIZE: 2048
NUM_LAYERS: 1
HIDDEN_SIZE1: 1024
HIDDEN_SIZE2: 512

TRAINING_PARAMS:
  batch_size: 32
  lr: 0.0001
  num_epochs: 40

CATEGORIES_DICT: {
        'l-pass': 0,
        'r-pass': 1,
        'l-spike': 2,
        'r_spike': 3,
        'l_set': 4,
        'r_set': 5,
        'l_winpoint': 6,
        'r_winpoint': 7
    }

ACTIONS_DICT: {
  "waiting": 0,
  "setting": 1,
  "digging": 2,
  "falling": 3,
  "spiking": 4,
  "blocking": 5,
  "jumping": 6,
  "moving": 7,
  "standing": 8
}

baseline1_logs: "logs/baselines_logs/baseline1_logs"
baseline3_logs: "logs/baselines_logs/baseline3_logs"
baseline4_logs: "logs/baselines_logs/baseline4_logs"
baseline5_logs: "logs/baselines_logs/baseline5_logs"
baseline6_logs: "logs/baselines_logs/baseline6_logs"

baseline1_assets: "assets/baselines_assets/baseline1"
baseline3_assets: "assets/baselines_assets/baseline3"

TRAINING_LOGS_PATH: "logs/training_logs"
MODELS_PATH: "models"

NUM_ACTIONS: 9
NUM_LABELS: 8

verbose: 1
