DATA_PATHS:
  videos_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/data/volleyball/volleyball_/videos"
  annot_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/data/volleyball/volleyball_tracking_annotation/volleyball_tracking_annotation"
  pooled_players_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/pooled_players_features"
  frame_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/frame_level_features"
  player_features_root: "/teamspace/studios/this_studio/Deep-Activity-Recognition/output/player_level_features"

TARGET_VIDEOS:
  train_ids: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31,
                 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
  val_ids: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
  test_ids: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

EXTRACTED_FEATURES_SIZE: 2048
HIDDEN_SIZE1: 1024
HIDDEN_SIZE2: 512
NUM_LAYERS: 1

TRAINING_PARAMS:
  batch_size: 64
  lr: 0.0001
  num_epochs: 40
  use_scheduler: True

CATEGORIES_DICT: {
        'l-pass': 0,
        'r-pass': 1,
        'l-spike': 2,
        'r_spike': 3,
        'l_set': 4,
        'r_set': 5,
        'l_winpoint': 6,
        'r_winpoint': 7
    }

ACTIONS_DICT: {
  "waiting": 0,
  "setting": 1,
  "digging": 2,
  "falling": 3,
  "spiking": 4,
  "blocking": 5,
  "jumping": 6,
  "moving": 7,
  "standing": 8
}

baseline1_logs: "logs/baselines_logs/baseline1_logs"
baseline3_logs: "logs/baselines_logs/baseline3_logs"
baseline4_logs: "logs/baselines_logs/baseline4_logs"
baseline5_logs: "logs/baselines_logs/baseline5_logs"
baseline6_logs: "logs/baselines_logs/baseline6_logs"
baseline7_logs: "logs/baselines_logs/baseline7_logs"
baseline8_logs: "logs/baselines_logs/baseline8_logs"

baseline1_assets: "assets/baselines_assets/baseline1"
baseline3_assets: "assets/baselines_assets/baseline3"
baseline4_assets: "assets/baselines_assets/baseline4"
baseline5_assets: "assets/baselines_assets/baseline5"
baseline6_assets: "assets/baselines_assets/baseline6"
baseline7_assets: "assets/baselines_assets/baseline7"
baseline8_assets: "assets/baselines_assets/baseline8"

b1_training_logs: "logs/training_logs/baseline1"
b3_training_logs: "logs/training_logs/baseline3"
b4_training_logs: "logs/training_logs/baseline4"
b5_training_logs: "logs/training_logs/baseline5"
b6_training_logs: "logs/training_logs/baseline6"
b7_training_logs: "logs/training_logs/baseline7"
b8_training_logs: "logs/training_logs/baseline8"

b1_best_models: "best_models/baseline1"
b3_best_models: "best_models/baseline3"
b4_best_models: "best_models/baseline4"
b5_best_models: "best_models/baseline5"
b6_best_models: "best_models/baseline6"
b7_best_models: "best_models/baseline7"
b8_best_models: "best_models/baseline8"

NUM_ACTIONS: 9
NUM_LABELS: 8

verbose: 1
